ci: fix pr comment step

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -22,7 +22,7 @@ jobs:
         run: yarn install
 
       - name: Run Vitest
-        run: yarn test --reporter=json > vitest-report.json || echo "test fail" is-test-fail
+        run: yarn test --reporter=json > vitest-report.json || echo "test fail" > is-test-fail
 
       - name: Get test results
         id: test-results
@@ -34,7 +34,7 @@ jobs:
           fi
 
       - name: Post PR comment
-        uses: thollander/actions-comment-pull-request@v2
+        uses: thollander/actions-comment-pull-request@v3
         with:
           message: |
             ## Vitest Results
